DROP TABLE IF EXISTS PUBLIC_INFO;
DROP TABLE IF EXISTS SECRET_INFO;

CREATE TABLE PUBLIC_INFO (
	RESOURCE_ID INT AUTO_INCREMENT PRIMARY KEY,
	CONTENTS VARCHAR(100) NOT NULL,
	CREATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SECRET_INFO (
	RESOURCE_ID INT AUTO_INCREMENT PRIMARY KEY,
	CONTENTS VARCHAR(100) NOT NULL,
	CREATE_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
